name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - 'release/**'

jobs:
  publish:
    uses: adwitkow/bannerlord-workflow-templates/.github/workflows/publish.yml@master
    permissions:
      actions: read
      contents: write
    with:
      nexus_file_id: "8082051"
      nexus_mod_id: "13632226211296"
    secrets:
      NEXUSMODS_API_KEY: ${{ secrets.NEXUSMODS_API_KEY }}
